# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: Adder.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'Adder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x41\x64\x64\x65r.proto\x12\x05\x41\x64\x64\x65r\".\n\nAddRequest\x12\x0f\n\x07num_one\x18\x01 \x01(\x05\x12\x0f\n\x07num_two\x18\x02 \x01(\x05\"\x1d\n\x0b\x41\x64\x64Response\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x35\n\x05\x41\x64\x64\x65r\x12,\n\x03\x41\x64\x64\x12\x11.Adder.AddRequest\x1a\x12.Adder.AddResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Adder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDREQUEST']._serialized_start=22
  _globals['_ADDREQUEST']._serialized_end=68
  _globals['_ADDRESPONSE']._serialized_start=70
  _globals['_ADDRESPONSE']._serialized_end=99
  _globals['_ADDER']._serialized_start=101
  _globals['_ADDER']._serialized_end=154
# @@protoc_insertion_point(module_scope)
